DROP DATABASE IF EXISTS PROJECT_MANAGER;
CREATE DATABASE PROJECT_MANAGER;
USE PROJECT_MANAGER;
CREATE TABLE BUILDING(
    ID CHAR(8) NOT NULL,
    BName VARCHAR(60) NOT NULL,
    BNo VARCHAR(5) NOT NULL,
    StName VARCHAR(100) NOT NULL,
    City VARCHAR(30) NOT NULL,
    ProvStTr VARCHAR(30) NOT NULL,
    Country VARCHAR(30) NOT NULL,
    PRIMARY KEY (ID)
);
CREATE TABLE ROOM (
    RoomNo VARCHAR(8) NOT NULL,
    Size CHAR(1) NOT NULL,
    EstCapacity INT NOT NULL,
    BuildingID CHAR(8) NOT NULL,
    PRIMARY KEY (RoomNO , BuildingID),
    CONSTRAINT BUILDINGFK FOREIGN KEY (BuildingID)
        REFERENCES BUILDING (ID)
        ON DELETE CASCADE ON UPDATE CASCADE
);
CREATE TABLE `MEMBER` (
    ID CHAR(8) NOT NULL,
    Fname VARCHAR(15) NOT NULL,
    Lname VARCHAR(15) NOT NULL,
    Gender VARCHAR(10),
    Email VARCHAR(320) NOT NULL,
    OrgID CHAR(10),
    PRIMARY KEY (ID)
);
CREATE TABLE `ADMIN` (
    `Position` VARCHAR(30) NOT NULL,
    ID CHAR(8) NOT NULL,
    CONSTRAINT ADMIN_PK PRIMARY KEY (ID , `Position`),
    CONSTRAINT ID_FK FOREIGN KEY (ID)
        REFERENCES MEMBER (ID)
        ON DELETE CASCADE ON UPDATE CASCADE
);
CREATE TABLE `ORGANIZATION` (
    ID CHAR(10) NOT NULL,
    OrgName VARCHAR(30) NOT NULL,
    `Description` VARCHAR(500),
    HRM_No VARCHAR(8),
    HRM_BID CHAR(8),
    PRIMARY KEY (ID),
    CONSTRAINT HMRM_FK
	FOREIGN KEY(HRM_NO, HRM_BID) REFERENCES ROOM(RoomNo, BuildingID)
	ON DELETE SET NULL ON UPDATE CASCADE
);
CREATE TABLE PROJECT (
    ID CHAR(8) NOT NULL,
    `Name` VARCHAR(30) NOT NULL,
    StartDate DATE,
    EndDate DATE,
    OrgID CHAR(10) NOT NULL,
    CONSTRAINT PROJECT_PK PRIMARY KEY (ID),
    CONSTRAINT ORG_ID_FK FOREIGN KEY(OrgID) REFERENCES `ORGANIZATION`(ID)
	ON DELETE SET NULL ON UPDATE CASCADE
);
CREATE TABLE TEAM (
    ID CHAR(8) NOT NULL,
    TName VARCHAR(30) NOT NULL,
    Size INT,
    Specialization VARCHAR(30) NOT NULL DEFAULT 'None',
    LeadID CHAR(8),
    OrgID CHAR(10) NOT NULL,
    ProjectID CHAR(8),
    PRIMARY KEY (ID),
    CONSTRAINT LEAD_FK FOREIGN KEY (LeadID)
        REFERENCES `ADMIN` (ID)
        ON DELETE SET NULL ON UPDATE CASCADE,
    CONSTRAINT ORG_FK FOREIGN KEY (OrgID)
        REFERENCES `ORGANIZATION` (ID)
        ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT PROJECT_FK2 FOREIGN KEY (ProjectID)
        REFERENCES PROJECT (ID)
        ON DELETE SET NULL ON UPDATE CASCADE
);
CREATE TABLE `EVENT` (
    EventID CHAR(10) NOT NULL,
    EventName CHAR(30) NOT NULL,
    No_Attendees INT,
    `Description` TEXT,
    StartDateTime TIMESTAMP,
    EndDateTime TIMESTAMP,
    HostID CHAR(10) NOT NULL,
    PlannerID CHAR(8) NOT NULL,
    PRIMARY KEY (EventID),
    CONSTRAINT HOST_FK FOREIGN KEY (HostID)
        REFERENCES `ORGANIZATION` (ID)
        ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT PLANNER_FK FOREIGN KEY (PlannerID)
        REFERENCES TEAM (ID)
        ON DELETE CASCADE ON UPDATE CASCADE
);
CREATE TABLE USES (
    RoomNo VARCHAR(8) NOT NULL,
    BuildingID CHAR(8) NOT NULL,
    StartTime TIMESTAMP NOT NULL,
    EndTime TIMESTAMP NOT NULL,
    EventID CHAR(8) NOT NULL,
    CONSTRAINT USESPK PRIMARY KEY (RoomNo , BuildingID , EventID),
    CONSTRAINT EVENT_FK FOREIGN KEY (EventID)
        REFERENCES `EVENT` (EventID)
        ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT ROOM_FK FOREIGN KEY (RoomNo , BuildingID)
        REFERENCES ROOM (RoomNo , BuildingID)
        ON DELETE CASCADE ON UPDATE CASCADE
);
CREATE TABLE BELONGS (
    Member_ID CHAR(8) NOT NULL,
    Team_ID CHAR(8) NOT NULL,
    CONSTRAINT TEAM_MEMBER_PK PRIMARY KEY (Member_ID , Team_ID),
    CONSTRAINT MEMBER_FK FOREIGN KEY (Member_ID)
        REFERENCES `MEMBER` (ID)
        ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT TEAM_ID_FK FOREIGN KEY (Team_ID)
        REFERENCES TEAM (ID)
        ON DELETE CASCADE ON UPDATE CASCADE
);
CREATE TABLE `COMPONENT` (
    PartID CHAR(16) NOT NULL,
    CName VARCHAR(30) NOT NULL,
    CType VARCHAR(30),
    Qty INT NOT NULL DEFAULT 1,
    OrgID CHAR(10) NOT NULL,
    PRIMARY KEY (PartID),
    CONSTRAINT ORG_FK3 FOREIGN KEY (OrgID)
        REFERENCES `ORGANIZATION` (ID)
        ON DELETE CASCADE ON UPDATE CASCADE
);
CREATE TABLE INVITED (
    MemberID CHAR(8) NOT NULL,
    EventID CHAR(10) NOT NULL,
    CONSTRAINT INVITEDPK PRIMARY KEY (MemberID , EventID),
    CONSTRAINT MEMBERFK2 FOREIGN KEY (MemberID)
        REFERENCES `MEMBER` (ID)
        ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT EVENTFK FOREIGN KEY (EventID)
        REFERENCES `EVENT` (EventID)
        ON DELETE CASCADE ON UPDATE CASCADE
);
CREATE TABLE DELIVERABLE (
    DName VARCHAR(30) NOT NULL,
    ProjectID CHAR(8) NOT NULL,
    TeamID CHAR(8) NOT NULL,
    StartDate TIMESTAMP,
    EndDate TIMESTAMP,
    CONSTRAINT DELIV_PK PRIMARY KEY (DName , ProjectID),
    CONSTRAINT PROJECT_FK FOREIGN KEY (ProjectID)
        REFERENCES PROJECT (ID)
        ON DELETE CASCADE ON UPDATE CASCADE
);
CREATE TABLE PREREQUISITE (
    DepDname VARCHAR(30) NOT NULL,
    DepDPID CHAR(8) NOT NULL,
    SrcDname VARCHAR(30) NOT NULL,
    SrcDPID CHAR(8) NOT NULL,
    CONSTRAINT PREREQ_PK PRIMARY KEY (DepDname , DepDPID , SrcDname , SrcDPID),
    CONSTRAINT DEPENDENT_FK FOREIGN KEY (DepDname , DepDPID)
        REFERENCES DELIVERABLE (DName , ProjectID)
        ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT SOURCE_FK FOREIGN KEY (SrcDname , SrcDPID)
        REFERENCES DELIVERABLE (DName , ProjectID)
        ON DELETE CASCADE ON UPDATE CASCADE
);
CREATE TABLE REQUIRES (
    PartID CHAR(16) NOT NULL,
    Qty INT NOT NULL,
    Dname VARCHAR(30) NOT NULL,
    DprojectID CHAR(8) NOT NULL,
    CONSTRAINT REQUIRESPK PRIMARY KEY (PartID , Dname , DprojectID),
    CONSTRAINT COMP_FK FOREIGN KEY (Dname , DprojectID)
        REFERENCES DELIVERABLE (Dname , projectID),
    CONSTRAINT DELIVERABLEFK FOREIGN KEY (Dname , DprojectID)
        REFERENCES DELIVERABLE (Dname , projectID)
        ON DELETE CASCADE ON UPDATE CASCADE
);
