DROP DATABASE IF EXISTS `project_manager`;
CREATE DATABASE `project_manager`;

CREATE TABLE BUILDING(
	ID		    CHAR(8)		    NOT NULL,
	BName	    VARCHAR(60),
	BNo		    VARCHAR(5),
	StName	    VARCHAR(100),
	City	    VARCHAR(30),
	ProvStTr	VARCHAR(30),
	Country	    VARCHAR(30),
    PRIMARY KEY(ID)
);

CREATE TABLE ROOM(
	RoomNo		VARCHAR(8) NOT NULL,
	Size		CHAR(1) NOT NULL,
	EstCapacity	INT NOT NULL,
    BuildingID	CHAR(8) NOT NULL,
	PRIMARY KEY(RoomNO, BuildingID),
    FOREIGN KEY(BuildingID) REFERENCES BUILDING(ID)
    ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE ORGANIZATION(
	ID			CHAR(10)		NOT NULL,
	OrgName		VARCHAR(30)		NOT NULL,
	Description	VARCHAR(500),
	HRM_No		VARCHAR(8),
	HRM_BID		CHAR(8),
    PRIMARY KEY(ID),
    FOREIGN KEY(HRM_No) REFERENCES ROOM(RoomNo)
    ON UPDATE CASCADE,
    FOREIGN KEY(HRM_BID) REFERENCES ROOM(BuildingID)
    ON UPDATE CASCADE
);

CREATE TABLE MEMBER(
    Fname		VARCHAR(15)		NOT NULL,
    Lname		VARCHAR(15)		NOT NULL,
    Email		VARCHAR(320)	NOT NULL,
	Gender		VARCHAR(10),
    OrgID		CHAR(10),
    Password	CHAR(127)		NOT NULL,
    PRIMARY KEY(Email),
    FOREIGN KEY(OrgID) REFERENCES ORGANIZATION(ID)
    ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE ADMIN(
	Email		   CHAR(8)		NOT NULL,
	PRIMARY KEY(Email),
	FOREIGN KEY(Email) REFERENCES MEMBER(Email)
	ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE PROJECT(
	ID		    CHAR(8)		    NOT NULL,
	PName		VARCHAR(30)		NOT NULL,
	StartDate	DATE,
	EndDate	    DATE,			
	OrgID		CHAR(10)		NOT NULL,
    PRIMARY KEY(ID),
    FOREIGN KEY(OrgID) REFERENCES ORGANIZATION(ID) 
    ON DELETE CASCADE ON UPDATE CASCADE
);
 
CREATE TABLE TEAM(
	ID		    CHAR(8)         NOT NULL,
	TName		VARCHAR(30)	    NOT NULL,
    Size		INTEGER,
	Specialization	VARCHAR(30)	NOT NULL 	DEFAULT "None",
	LeadEmail		CHAR(8)        NOT NULL,
	OrgID		CHAR(10)	    NOT NULL,
	ProjectID	CHAR(8),	    
	PRIMARY KEY(ID),
    FOREIGN KEY(LeadEmail) REFERENCES ADMIN(Email)
    ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY(OrgID) REFERENCES ORGANIZATION(ID)
    ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY(ProjectID) REFERENCES PROJECT(ID)
    ON DELETE SET NULL ON UPDATE CASCADE
);

CREATE TABLE BELONGS(
	MEmail	CHAR(8) 	NOT NULL,
	Team_ID		CHAR(8)		NOT NULL,
	PRIMARY KEY(MEmail, Team_ID),
	FOREIGN KEY(MEmail) REFERENCES MEMBER(Email)
    ON DELETE 	CASCADE ON UPDATE CASCADE,
	FOREIGN KEY(Team_ID) REFERENCES TEAM(ID)
    ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE EVENT_(
	EventID		        CHAR(10)	NOT NULL,
	EventName			CHAR(30)    NOT NULL,
	No_Attendees		INTEGER		    NOT NULL DEFAULT 0,
	Description			TINYTEXT,
	StartDateTime		DATETIME	NOT NULL,
    EndDateTime 		DATETIME	NOT NULL,
	HostID			    CHAR(10)	NOT NULL,
	PlannerID		    CHAR(8)		NOT NULL,
	PRIMARY KEY(EventID),
	FOREIGN KEY(HostID) REFERENCES ORGANIZATION(ID)
	ON DELETE CASCADE ON UPDATE CASCADE,
	FOREIGN KEY(PlannerID) REFERENCES TEAM(ID)
    ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE EVENT_USES(
	RoomNo	    VARCHAR(8)	NOT NULL,
	BuildingID	CHAR(8)		NOT NULL,
	EventID 	CHAR(8)		NOT NULL,
    PRIMARY KEY(RoomNo, BuildingID, EventID),
    FOREIGN KEY(EventID) REFERENCES EVENT_(EventID) 
    ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY(RoomNo, BuildingID) REFERENCES ROOM(RoomNo, BuildingID)
    ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE INVITATION(
    MEmail       VARCHAR(8) NOT NULL,
    EventID         VARCHAR(8) NOT NULL,
    FOREIGN KEY(MEmail) REFERENCES MEMBER(Email)
    ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY(EventID) REFERENCES EVENT_(EventID)
    ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE DELIVERABLE(
	DName		VARCHAR(30)	NOT NULL,
	ProjectID	CHAR(8)		NOT NULL,
	TeamID	    CHAR(8),
	StartDate	DATE   NOT NULL,
	EndDate	    DATE   NOT NULL,
	PRIMARY KEY(DName, ProjectID),
	FOREIGN KEY(ProjectID) REFERENCES PROJECT(ID) 
	ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY(TeamID) REFERENCES TEAM(ID)
    ON DELETE SET NULL ON UPDATE CASCADE
);

CREATE TABLE PREREQUISITE(
	DepDname 	VARCHAR(30) 	NOT NULL,
	DepDPID		CHAR(8) 		NOT NULL,
	SrcDname	VARCHAR(30) 	NOT NULL,
	SrcDPID		CHAR(8) 		NOT NULL,
	PRIMARY KEY(DepDname, DepDPID, SrcDname, SrcDPID),
	FOREIGN KEY(DepDname, DepDPID) REFERENCES DELIVERABLE(DName, ProjectID)	
    ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY(SrcDname, SrcDPID) REFERENCES DELIVERABLE(DName, ProjectID)
    ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE COMPONENT(
	PartID		CHAR(16)	NOT NULL,
	CName		VARCHAR(30) NOT NULL,		
	CType		VARCHAR(30),
	Qty			INTEGER			 NOT NULL DEFAULT 1,
	OrgID		CHAR(10)		NOT NULL,	
	PRIMARY KEY(PartID),
	FOREIGN KEY(OrgID) REFERENCES ORGANIZATION(ID)
	ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE REQUIRES (
    PartID CHAR(16) NOT NULL,
    Qty INTEGER NOT NULL,
    Dname VARCHAR(30) NOT NULL,
    DprojectID CHAR(8) NOT NULL,
    PRIMARY KEY (PartID , Dname , DprojectID),
    FOREIGN KEY (Dname , DprojectID) REFERENCES DELIVERABLE (Dname , projectID),
    FOREIGN KEY (PartID) REFERENCES COMPONENT(PartID)
    ON DELETE CASCADE ON UPDATE CASCADE
);